// dead-deps-scan 判定结果（work/maps/slim-perf/dead-deps.md）：激活面缺席 +
// require 链不触达 + linux 删后冒烟 CLEAN。win32 boot 复核为 follow-up（见报告 §平台覆盖）。
// win32 复核优先：'@deepseek-ai/dsh-tool-pwsh'、'@deepseek-ai/dsh-pwsh-sandbox'（pwsh 家族近邻）。
export const DEAD_DEPS = new Set([
  // ── g1 web/office/libreoffice（linux 231MB + win32 变体 330MB）──
  '@deepseek-ai/dsh-api-gateway', '@deepseek-ai/dsh-api-remotes',
  '@deepseek-ai/dsh-api-session-controller', '@deepseek-ai/dsh-api-settings-controller',
  '@deepseek-ai/dsh-api-terminal-controller', '@deepseek-ai/dsh-api-workspace-controller',
  '@deepseek-ai/dsh-api-workspace-files', '@deepseek-ai/dsh-authorization',
  '@deepseek-ai/dsh-client-connection', '@deepseek-ai/dsh-client-file-upload',
  '@deepseek-ai/dsh-client-hmr', '@deepseek-ai/dsh-client-locale',
  '@deepseek-ai/dsh-client-modules', '@deepseek-ai/dsh-client-resources',
  '@deepseek-ai/dsh-client-ui-agent-preset', '@deepseek-ai/dsh-client-ui-approval',
  '@deepseek-ai/dsh-client-ui-attachment', '@deepseek-ai/dsh-client-ui-brand-official',
  '@deepseek-ai/dsh-client-ui-chat', '@deepseek-ai/dsh-client-ui-commands',
  '@deepseek-ai/dsh-client-ui-conversation', '@deepseek-ai/dsh-client-ui-cordis',
  '@deepseek-ai/dsh-client-ui-deliverables', '@deepseek-ai/dsh-client-ui-directory-picker-browse',
  '@deepseek-ai/dsh-client-ui-directory-picker-native', '@deepseek-ai/dsh-client-ui-goal',
  '@deepseek-ai/dsh-client-ui-input-trigger', '@deepseek-ai/dsh-client-ui-jobs',
  '@deepseek-ai/dsh-client-ui-layout', '@deepseek-ai/dsh-client-ui-message-feedback',
  '@deepseek-ai/dsh-client-ui-model-selection', '@deepseek-ai/dsh-client-ui-open-in-app',
  '@deepseek-ai/dsh-client-ui-permission-presets', '@deepseek-ai/dsh-client-ui-plan',
  '@deepseek-ai/dsh-client-ui-plugin-manager', '@deepseek-ai/dsh-client-ui-primitives',
  '@deepseek-ai/dsh-client-ui-reference', '@deepseek-ai/dsh-client-ui-renderer',
  '@deepseek-ai/dsh-client-ui-schedule', '@deepseek-ai/dsh-client-ui-session',
  '@deepseek-ai/dsh-client-ui-settings', '@deepseek-ai/dsh-client-ui-settings-general',
  '@deepseek-ai/dsh-client-ui-settings-models', '@deepseek-ai/dsh-client-ui-settings-plugin-inventory',
  '@deepseek-ai/dsh-client-ui-settings-plugins', '@deepseek-ai/dsh-client-ui-settings-unarchive-sessions',
  '@deepseek-ai/dsh-client-ui-sidebar', '@deepseek-ai/dsh-client-ui-sidebar-browser',
  '@deepseek-ai/dsh-client-ui-sidebar-documentpreview', '@deepseek-ai/dsh-client-ui-sidebar-files',
  '@deepseek-ai/dsh-client-ui-sidebar-right', '@deepseek-ai/dsh-client-ui-sidebar-terminal',
  '@deepseek-ai/dsh-client-ui-skill', '@deepseek-ai/dsh-client-ui-slots',
  '@deepseek-ai/dsh-client-ui-subagent', '@deepseek-ai/dsh-client-ui-theme',
  '@deepseek-ai/dsh-client-ui-tool', '@deepseek-ai/dsh-client-ui-trajectory',
  '@deepseek-ai/dsh-client-ui-user-questions', '@deepseek-ai/dsh-client-ui-workflow-run',
  '@deepseek-ai/dsh-client-ui-workspace', '@deepseek-ai/dsh-cordis-client-runner',
  '@deepseek-ai/dsh-cordis-host-runner', '@deepseek-ai/dsh-experimental-agent-team',
  '@deepseek-ai/dsh-experimental-agent-team-profile', '@deepseek-ai/dsh-experimental-agent-team-web-profile',
  '@deepseek-ai/dsh-experimental-client-ui-agent-team', '@deepseek-ai/dsh-experimental-tool-agent-team',
  '@deepseek-ai/dsh-file-reference', '@deepseek-ai/dsh-file-reference-local',
  '@deepseek-ai/dsh-hmr', '@deepseek-ai/dsh-host-directory-picker',
  '@deepseek-ai/dsh-host-directory-picker-auto', '@deepseek-ai/dsh-host-directory-picker-browse',
  '@deepseek-ai/dsh-host-directory-picker-native', '@deepseek-ai/dsh-host-frontend-static',
  '@deepseek-ai/dsh-host-open-in-app', '@deepseek-ai/dsh-host-webserver',
  '@deepseek-ai/dsh-native-command', '@deepseek-ai/dsh-office-to-pdf',
  '@deepseek-ai/dsh-session-log-export', '@deepseek-ai/dsh-session-stats',
  '@deepseek-ai/dsh-session-turn-outline', '@deepseek-ai/dsh-web-app',
  '@deepseek-ai/dsh-web-frontend', '@deepseek-ai/dsh-workspace',
  '@deepseek-ai/dsh-workspace-changes', '@deepseek-ai/libreoffice-kit',
  '@deepseek-ai/libreoffice-kit-wasm', '@deepseek-ai/libreoffice-kit-win32-x64',
  '@swc/helpers', '@xterm/addon-serialize', 'base64-js', 'brotli', 'bundle-name',
  'bytes', 'chokidar', 'clone', 'compressible', 'compression', 'content-type',
  'debug', 'default-browser', 'default-browser-id', 'define-lazy-prop', 'destroy',
  'dfa', 'diff', 'fast-deep-equal', 'fflate', 'fontkit', 'is-docker', 'is-in-ssh',
  'is-inside-container', 'is-wsl', 'mime-db', 'mime-types', 'ms', 'negotiator',
  'on-headers', 'open', 'pako', 'picomatch', 'powershell-utils', 'readdirp',
  'restructure', 'run-applescript', 'safe-buffer', 'saxes', 'tiny-inflate',
  'unicode-properties', 'unicode-trie', 'vary', 'ws', 'wsl-utils', 'xmlchars',
  // ── g2 otel + protobufjs（39.7MB）──
  '@deepseek-ai/dsh-session-telemetry', '@deepseek-ai/dsh-session-telemetry-otel',
  '@opentelemetry/api', '@opentelemetry/api-logs', '@opentelemetry/core',
  '@opentelemetry/exporter-logs-otlp-http', '@opentelemetry/otlp-exporter-base',
  '@opentelemetry/otlp-transformer', '@opentelemetry/resources',
  '@opentelemetry/sdk-logs', '@opentelemetry/sdk-metrics', '@opentelemetry/sdk-trace',
  '@opentelemetry/semantic-conventions', '@protobufjs/aspromise', '@protobufjs/base64',
  '@protobufjs/codegen', '@protobufjs/eventemitter', '@protobufjs/fetch',
  '@protobufjs/float', '@protobufjs/path', '@protobufjs/pool', '@protobufjs/utf8',
  'long', 'protobufjs',
  // ── g3 pi-ai 多供应商链（69MB）──
  '@deepseek-ai/dsh-llm-pi-ai', '@earendil-works/pi-ai', '@earendil-works/pi-telemetry',
  '@anthropic-ai/sdk', '@google/genai', 'openai', 'agent-base', 'bignumber.js',
  'data-uri-to-buffer', 'eventsource', 'extend', 'fetch-blob', 'formdata-polyfill',
  'gaxios', 'gcp-metadata', 'google-auth-library', 'google-logging-utils',
  'http-proxy-agent', 'https-proxy-agent', 'json-bigint', 'jwa', 'jws',
  'node-domexception', 'node-fetch', 'typebox', 'undici-types', 'web-streams-polyfill',
  // ── g4 webhook/octokit/smithy/aws + mcp/acp（41.7MB）──
  '@deepseek-ai/dsh-webhook', '@deepseek-ai/dsh-webhook-github',
  '@deepseek-ai/dsh-mcp-client', '@deepseek-ai/dsh-acp', '@deepseek-ai/dsh-acp-app',
  '@modelcontextprotocol/client', '@modelcontextprotocol/core', '@agentclientprotocol/sdk',
  '@octokit/openapi-types', '@octokit/openapi-webhooks-types', '@octokit/request-error',
  '@octokit/types', '@octokit/webhooks', '@octokit/webhooks-methods',
  '@smithy/core', '@smithy/credential-provider-imds', '@smithy/fetch-http-handler',
  '@smithy/is-array-buffer', '@smithy/node-http-handler', '@smithy/signature-v4',
  '@smithy/types', '@smithy/util-buffer-from', '@smithy/util-utf8',
  '@aws-sdk/client-bedrock-runtime', '@aws-sdk/core', '@aws-sdk/credential-provider-env',
  '@aws-sdk/credential-provider-http', '@aws-sdk/credential-provider-ini',
  '@aws-sdk/credential-provider-login', '@aws-sdk/credential-provider-node',
  '@aws-sdk/credential-provider-process', '@aws-sdk/credential-provider-sso',
  '@aws-sdk/credential-provider-web-identity', '@aws-sdk/eventstream-handler-node',
  '@aws-sdk/middleware-eventstream', '@aws-sdk/middleware-websocket',
  '@aws-sdk/nested-clients', '@aws-sdk/signature-v4-multi-region', '@aws-sdk/token-providers',
  '@aws-sdk/types', '@aws-sdk/util-locate-window', '@aws-sdk/xml-builder',
  '@aws-crypto/sha256-browser', '@aws-crypto/sha256-js', '@aws-crypto/supports-web-crypto',
  '@aws-crypto/util', '@aws/lambda-invoke-store',
  'buffer-equal-constant-time', 'cross-spawn', 'ecdsa-sig-formatter', 'fast-sha256',
  'isexe', 'jose', 'pkce-challenge', 'shebang-command', 'shebang-regex',
  'standardwebhooks', 'which',
  // ── g5 dsh-base 长尾未激活插件（10MB，含 4 个 DISABLED 条目包）──
  '@deepseek-ai/cordis-plugin-include', '@deepseek-ai/dsh-agent-default-model',
  '@deepseek-ai/dsh-agent-instructions', '@deepseek-ai/dsh-agent-presets',
  '@deepseek-ai/dsh-agent-tool-presentation', '@deepseek-ai/dsh-base',
  '@deepseek-ai/dsh-bash-local', '@deepseek-ai/dsh-bash-sandbox',
  '@deepseek-ai/dsh-chunked-list', '@deepseek-ai/dsh-command-compact',
  '@deepseek-ai/dsh-command-feedback', '@deepseek-ai/dsh-command-goal',
  '@deepseek-ai/dsh-commands', '@deepseek-ai/dsh-credentials-local',
  '@deepseek-ai/dsh-deque', '@deepseek-ai/dsh-fs', '@deepseek-ai/dsh-fs-local',
  '@deepseek-ai/dsh-fs-observation-policy', '@deepseek-ai/dsh-fs-sandbox',
  '@deepseek-ai/dsh-goal', '@deepseek-ai/dsh-goal-round-driver',
  '@deepseek-ai/dsh-headless', '@deepseek-ai/dsh-hook-protocol',
  '@deepseek-ai/dsh-hooks-claude-code', '@deepseek-ai/dsh-hooks-codex',
  '@deepseek-ai/dsh-message-feedback', '@deepseek-ai/dsh-output-retention',
  '@deepseek-ai/dsh-package-manifest', '@deepseek-ai/dsh-permission-presets',
  '@deepseek-ai/dsh-persona', '@deepseek-ai/dsh-plan-mode',
  '@deepseek-ai/dsh-plugin-package-inventory-deepseek', '@deepseek-ai/dsh-ptc-runtime',
  '@deepseek-ai/dsh-ptc-runtime-node', '@deepseek-ai/dsh-pwsh-sandbox',
  '@deepseek-ai/dsh-repeat-tool-reminder', '@deepseek-ai/dsh-schedule',
  '@deepseek-ai/dsh-sdk-app', '@deepseek-ai/dsh-sdk-jsonrpc-server',
  '@deepseek-ai/dsh-session-checkpoint-policy', '@deepseek-ai/dsh-session-log-deepseek',
  '@deepseek-ai/dsh-session-projection-cache', '@deepseek-ai/dsh-session-query',
  '@deepseek-ai/dsh-session-query-sqlite', '@deepseek-ai/dsh-session-reference',
  '@deepseek-ai/dsh-session-title-first-prompt-llm', '@deepseek-ai/dsh-session-title-llm',
  '@deepseek-ai/dsh-settings', '@deepseek-ai/dsh-settings-file',
  '@deepseek-ai/dsh-shell-env', '@deepseek-ai/dsh-skill', '@deepseek-ai/dsh-skill-badge',
  '@deepseek-ai/dsh-skill-filesystem', '@deepseek-ai/dsh-spill',
  '@deepseek-ai/dsh-spill-local', '@deepseek-ai/dsh-spill-policy',
  '@deepseek-ai/dsh-storage', '@deepseek-ai/dsh-storage-domain',
  '@deepseek-ai/dsh-storage-json', '@deepseek-ai/dsh-subagent',
  '@deepseek-ai/dsh-subagent-fork-in-process', '@deepseek-ai/dsh-subagent-in-process-driver',
  '@deepseek-ai/dsh-subagent-spawn-in-process', '@deepseek-ai/dsh-time-context',
  '@deepseek-ai/dsh-tmux-context', '@deepseek-ai/dsh-tool-ask-user',
  '@deepseek-ai/dsh-tool-bash', '@deepseek-ai/dsh-tool-call-timeout-policy',
  '@deepseek-ai/dsh-tool-cordis', '@deepseek-ai/dsh-tool-fs',
  '@deepseek-ai/dsh-tool-fs-search', '@deepseek-ai/dsh-tool-goal',
  '@deepseek-ai/dsh-tool-jobs', '@deepseek-ai/dsh-tool-present',
  '@deepseek-ai/dsh-tool-pwsh', '@deepseek-ai/dsh-tool-ralph',
  '@deepseek-ai/dsh-tool-skill', '@deepseek-ai/dsh-tool-str-replace-editor',
  '@deepseek-ai/dsh-tool-subagent', '@deepseek-ai/dsh-tool-subagent-control',
  '@deepseek-ai/dsh-tool-todo', '@deepseek-ai/dsh-tool-workflow',
  '@deepseek-ai/dsh-typert-loader', '@deepseek-ai/dsh-typert-registry',
  '@deepseek-ai/dsh-user-approval', '@deepseek-ai/dsh-user-questions',
  '@deepseek-ai/dsh-util-time', '@deepseek-ai/dsh-util-workspace-path',
  '@deepseek-ai/dsh-workflow', '@deepseek-ai/dsh-workflow-ptc',
  // ── g6 vendor 尾（linux 11.7MB / win32 6.2MB）──
  '@babel/code-frame', '@babel/helper-validator-identifier', '@babel/runtime',
  '@stablelib/base64', '@standard-schema/spec', '@types/node', '@types/retry',
  '@vscode/ripgrep', '@vscode/ripgrep-linux-x64', '@vscode/ripgrep-win32-x64',
  'bowser', 'js-tokens', 'json-schema-to-ts', 'p-retry', 'partial-json',
  'picocolors', 'retry', 'ts-algebra',
])
